### ISSUE TITLE
LRU caches should use a power of two

### ISSUE THREAD

**Issue by zoni** [Vaelor/errbot-mattermost-backend#1]
See for example https://github.com/Vaelor/errbot-mattermost-backend/blob/1db8d33cbdaf59b4e1a51f350b8efb50c2a0ec96/mattermost.py#L346. 

The official [python docs](https://docs.python.org/3/library/functools.html#functools.lru_cache) state, _"The LRU feature performs best when maxsize is a power-of-two"_.

**Comment by Vaelor** [comment]
FYI: This is also the case in
https://github.com/errbotio/errbot/blob/master/errbot/backends/slack.py#L582

**Comment by zoni** [comment]
As of https://github.com/errbotio/errbot/commit/ee6b2eaf625f6f5144f396cc8f24c31fe64abf99 that's no longer the case. :grin: 

Thanks for the heads up!
