### ISSUE TITLE
Potentially misleading error message

### ISSUE THREAD

**Issue by zoni** [Vaelor/errbot-mattermost-backend#2]
`serve_once` [catches MattermostApiResponseError](https://github.com/Vaelor/errbot-mattermost-backend/blob/1db8d33cbdaf59b4e1a51f350b8efb50c2a0ec96/mattermost.py#L381-L384) and raises `TeamDoesNotExistError` when this occurs but I believe `MattermostApiResponseError` could also be triggered by transient errors such as network issues or a 500 internal server error on mattermost server. These would incorrectly get reported as `TeamDoesNotExistError` which would be misleading.

**Comment by zoni** [comment]
Thinking about the API, `getTeamObjectByName` itself should probably return such an exception (inheriting from `MattermostApiResponseError`) so it's easy for consumers of the client to catch.

**Comment by Vaelor** [comment]
Yeah I guess that should be changed, but I am currently unsure how to handle the mattermost-api/client at all. Currently I am somehow unhappy with it.
I have also thought about switching over to the official mattermost api, which I could generate with swagger.
They have a .yaml file for that, but I found it somehow really ugly, with functionnames like
`teams_team_id_channels_channel_id_users_not_in_channel_offset_limit_post`, and it is not complete..
