### ISSUE TITLE
Threaded Messages

### ISSUE THREAD

**Issue by Vaelor** [Vaelor/errbot-mattermost-backend#24]
Implement threaded messages like in the slack backend: https://github.com/errbotio/errbot/commit/46302b04255c021d691189fb7d34c0b69017e43b#diff-4d2174262014c51fc8b38e02b99962bd

**Comment by gpr** [comment]
Hi @Vaelor, I forked your project and added the support of Threaded messages, but I did some sources format change to be compliant with pep8 that you maybe don't want, hence I will rewrite my history to separate functional changes from others before creating a merge request. See https://github.com/gpr/errbot-mattermost-backend.

**Comment by Vaelor** [comment]
Hey, thanks a lot!!
I just had a look at your fork, you even added a test environment, that's awesome :-)
I had a look at the diff, it does look fine to me didn't try it out yet though.

As for the whitespace changes - I would prefer not to change them. :-)
Any other formatting changes  (I did not look trough your formatting change diffs ;-) ) to be compliant to PEP 8 that's fine, but I would love to keep the tabs.

**Comment by gpr** [comment]
I removed all formatting stuff in the PR #35, let me know if you need any modification to get it merged
