### ISSUE TITLE
Bot Mentions Not Working

### ISSUE THREAD

**Issue by btotharye** [Vaelor/errbot-mattermost-backend#27]
Seems like actually mentioning at the bot doesn't work.  You have to do !cmd, is this expected?  Seems like from Readme its a known issue so I will try to help fix it.

I don't mind going through and helping fix it just wasn't sure if I was missing something, doesn't appear to happen on my slack version of the bot.

**Comment by btotharye** [comment]
Looks like cause of how mattermost does it, it doesn't actually treat it like a mention per say but just does a @nameofbot

`
2017-09-11 17:40:02,141 DEBUG    errbot.core               *** text = @mycrofthelper help
`

**Comment by Vaelor** [comment]
The issue in the readme is regarding channelmentions like `~town-square` (if you do want to do something about it, go ahead :-D ;-) )
Mhh I don't  have a slack setup so I can't really check if this is the case.
Having a quick look at your config (assuming your errbot-slack repository is the one you say is working)
https://github.com/btotharye/errbot-slack/blob/6dd50221e21c46be727e772a8c65e3048e6a2bb7/config.py#L66

You explicitly say `BOT_ALT_PREFIXES = ('@geekbot',)` which would explain why the `@` works.
If you do the same for mattermost, it should work too. I assume, if you remove this line from your slack `config.py`, it stops working, too.

**Comment by btotharye** [comment]
doh lol sorry

**Comment by btotharye** [comment]
this works by adding that sorry :(
