### ISSUE TITLE
Support for card

### ISSUE THREAD

**Issue by inkhey** [Vaelor/errbot-mattermost-backend#28]
Mattermost backend doesn't have specific support for card .
Examples of errbot card here
https://github.com/errbotio/err-cards-tester

Mattermost attachment seems very close to errbot card 
https://docs.mattermost.com/developer/message-attachments.html

**Comment by Vaelor** [comment]
Yes you are right. I will have to look into this, It never occured to me that cards would be called attachments here.

**Comment by Vaelor** [comment]
Hey @inkhey 

I made a - to be honest, not a perfect one - solution.
Mattermost currently only seems to support cards (attachments) over webhooks/slash commands.
To make them work, you need to create an incoming webhook in mattermost and add it to your `BOT_IDENTITY: {'cards_hook': 'myHookId', ...}` in `config.py`.
Hopefully Mattermost makes it somehow available over the api someday.

I hope you can work with this solution! Let me know if I can improve anything!

**Comment by Vaelor** [comment]
Oh and you need to `pip install -U mattermostdriver` and install version 2.3.0

**Comment by inkhey** [comment]
Thanks @Vaelor  for working on this.
Just try it now but failed to make it work. Don't really know where the problem is, it just return the card with normal text backend. Nothing look interesting in log.

EDIT: Just forgot to update mattermost backend !!!

**Comment by inkhey** [comment]
There is just something not really cool with this, the card were always send to the same room, the one linked to the hook. May be better to only send card to the correct room and send old backend to the others, it's far from perfect but it's less strange than returning all to the same place.

**Comment by Vaelor** [comment]
@inkhey Ok I will have a look at it again this weekend, I just tested it against a single room. But I think it should be possible to post into other rooms with webhooks.. not sure though. 

Other then that, I asked the Mattermost devs if they are working on supporting cards over the api, which sadly they do not (yet). So we are stuck with a webhook for now.

**Comment by Vaelor** [comment]
Hey @inkhey!

I changed a little bit and now you should be able to pass a channel to which you want to send it.
You have to set the 'to' parameter on the card to a valid identifier. Currently this works only with channels, I tested usernames but did not yet find out if that is possible.

A small example plugin:
``` Python
class Cardtest(BotPlugin):
    @arg_botcmd('channel', type=str)
    def cardtest(self, message, channel):
       identifier = self.build_identifier(channel)
       self.send_card(body="Card Test", to=identifier)

# Usage example: !cardtest ~town-square
```

**Comment by inkhey** [comment]
Thanks, it's working now :-) .

**Comment by Vaelor** [comment]
Awesome :-)
