### ISSUE TITLE
Space instead of Tabs

### ISSUE THREAD

**Issue by inkhey** [Vaelor/errbot-mattermost-backend#29]
Spaces are the preferred indentation method for python according to pep8.
https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces
It Seems to me better to choose space in order to not disturb people (errbot use space also).

**Comment by Vaelor** [comment]
My choice of indentation is not the popular one, I know that. I do have my own subjective reasons why I chose not to follow the pep8 recommendation in this matter and I do not plan to change this.
Also, I do not intend to start a discussion about why and what the pros and cons are.
