### ISSUE TITLE
Unable to get bot channels list

### ISSUE THREAD

**Issue by inkhey** [Vaelor/errbot-mattermost-backend#30]
I wanted to have channels list of my bot. My code work correctly on slack backend but not
on this one.

```
File "/home/inkey/Documents/IM/errbot/plugins/monplugin/monplugin.py", line 21, in message
    rooms = [str(room) for room in self.rooms()]
  File "/home/inkey/.local/share/virtualenvs/errbot/lib/python3.5/site-packages/errbot/botplugin.py", line 631, in rooms
    return self._bot.rooms()
  File "/home/inkey/Documents/IM/errbot/extra-backend/errbot-mattermost-backend/mattermost.py", line 532, in rooms
    rooms = self.channels(joined_only=True)
  File "/home/inkey/Documents/IM/errbot/extra-backend/errbot-mattermost-backend/mattermost.py", line 522, in channels
    channels.extend(self.driver.api['channels'].get_channels_for_user(user_id=self.userid, team_id=self.teamid))
AttributeError: 'Channels' object has no attribute 'get_channels_for_user'
```

**Comment by Vaelor** [comment]
For a quick fix you could change this line:
https://github.com/Vaelor/errbot-mattermost-backend/blob/9cc3c6c799b9259272b2d4076688f83b4a12ee7a/mattermost.py#L522
to
`channels.extend(self.driver.api['channels'].get_channel_for_user(user_id=self.userid, team_id=self.teamid))` (Remove the s from `get_channels_for_user`)

This isn't exactly a bug with the backend but the mattermostdriver:
https://github.com/Vaelor/python-mattermost-driver/blob/e40d6488b02e55efb1bc69c55577f0870df08e04/src/mattermostdriver/endpoints/channels.py#L131
I will keep this open and make a duplicate there.
https://github.com/Vaelor/python-mattermost-driver/issues/9

**Comment by Vaelor** [comment]
I fixed the mattermostdriver.
You need to update the dependency, it should be enough doing a `pip install -U mattermostdriver` in the virtual env you installed errbot in.
It should update to 2.1.2 which contains a fix.
