### ISSUE TITLE
msg.frm.room.occupants returns error

### ISSUE THREAD

**Issue by Betriebsrat** [Vaelor/errbot-mattermost-backend#36]
As soon as you try to do something with msg.frm.room.occupants the following error appears:  

> 
> File "...errbot-mattermost-backend/src/mattermostRoom.py", line 118, in occupants
>     params={'page': start, 'per_page': user_page_limit}
> ValueError: dictionary update sequence element #0 has length 8; 2 is required

example code:

>     def helper_other_occupants_in_room(self, msg):
>         """returns all mention names of other occupants in the room"""
>         other_occupants = [o.person for o in msg.frm.room.occupants if o.nick != self.bot_identifier.nick]
>         return other_occupants

**Comment by Vaelor** [comment]
Thanks, I see the error.
Quite dumb, I try to update a dict with an array... Not sure what I did there.
Since I already see where the error is, I guess I will fix this sometime today.

**Comment by Vaelor** [comment]
Please have a look if the latest commit fixes this for you, in my case your example code worked for me.

**Comment by Betriebsrat** [comment]
this fixes it.
Thanks alot!

**Comment by Vaelor** [comment]
No problem, glad that worked :-)
