### ISSUE TITLE
Backend unaware of bot/hook messages

### ISSUE THREAD

**Issue by Betriebsrat** [Vaelor/errbot-mattermost-backend#38]
I tried to catch webhook or other bot messages which are triggered within mattermost with re_botcmd.
Sadly i had no success.

Also i saw:
https://github.com/Vaelor/errbot-mattermost-backend/blob/master/mattermost.py#L196

Is there any way i can help to implement this?

**Comment by Betriebsrat** [comment]
needs further research
(only occurs on failed gitlab builds, commit hooks are fine)

**Comment by Vaelor** [comment]
Sorry for the late reply, I am currently packed with work.
Bot accounts are currently discussed in mattermost in their official mattermost channel. This is rather recent so I guess it will  take a few days until these are implemented
https://pre-release.mattermost.com/core/channels/bot-accounts

**Comment by Betriebsrat** [comment]
This might not be an mattermost backend issue i reported the behaivor to gitlab via:
https://gitlab.com/gitlab-org/gitlab-ce/issues/46664
