### ISSUE TITLE
Slow responses from errbot

### ISSUE THREAD

**Issue by abd6982** [Vaelor/errbot-mattermost-backend#39]
I am using this backend to connect my errbot to mattermost. Basically, my bot behaves something like this. I created a plugin and defined a `callback_message` to intercept messages and updates from Mattermost. Whenever an update comes in `callback_message`, errbot calls an API which gives back some response and this response is sent to Mattermost. But errbot is taking very long in this, usually 4-5 seconds in between getting updates from Mattermost and sending back reply. I can confirm this is not a problem with the API being called because previously I was using it with **Botkit** and the responses were instant. Can anybody help me with this issue? Is this normal? Or is there a problem with this behavior?

**Comment by abd6982** [comment]
Well, it was slow locally. I hosted it on an amazon ec2 instance and the responses were split-second fast. I just wonder why it is slow locally when botkit is fast locally as well. My problem is solved as I had to host it on a server anyway. Closing this issue.

**Comment by Vaelor** [comment]
I encountered this a few times before, never used any other backend then the mattermost one for errbot (except the Text for testing), so not sure if this is solemnly a problem of this backend/errbot in general/some plugins. I threw out a bunch of plugins I tried after seeing it was sometimes slow, which improved speed too.
