### ISSUE TITLE
Access to channel 'notifications'? Ex.: "xyz joined the team"

### ISSUE THREAD

**Issue by thufir-hawat** [Vaelor/errbot-mattermost-backend#42]
Like  this:
![image](https://user-images.githubusercontent.com/35777154/52790688-74bfc380-3067-11e9-9b4e-43f1fdee7dc0.png)
I'd like to have the bot react to the mentions and send the users a message. Is there a way to do that with your plugin?

**Comment by Vaelor** [comment]
I don't think so, though I am not 100% sure.

I can't test it at the moment, but, your message above should trigger this event:
https://github.com/Vaelor/errbot-mattermost-backend/blob/master/mattermost.py#L93
which, in turn calls the `callback_room_joined`, but as far as I still understand that line, only if the bot is the user joining the room.
https://github.com/Vaelor/errbot-mattermost-backend/blob/master/mattermost.py#L109
If it is another user, it shouldn't trigger.
So, this probably would need some kind of code change...

**Comment by Vaelor** [comment]
Not sure if it is an alternative:
You could use https://github.com/Vaelor/python-mattermost-driver
and access the websocket events directly (not sure if you are dead set on using errbot for that)
`foo.init_websocket(event_handler)` Where your event_handler could do anything you like.
https://api.mattermost.com/#tag/WebSocket - The list of available events is quite big.
