### ISSUE TITLE
Support for multiple teams

### ISSUE THREAD

**Issue by Atlas974** [Vaelor/errbot-mattermost-backend#50]
Hi,

I'm looking to use my bot in multiple teams on Mattermost. It doesn't seem like you can do it the way it is currently implemented. Is that right? Are there any plans to add this functionality? 

Thank you.

**Comment by Vaelor** [comment]
Hey @Atlas974 There was a PR a while back which tried to implement that and when initially working on this project I tried it, too.
In my opinion it had to many issues/problems to solve, but if someone has an idea how to solve that, sure.
But as of right now, I myself don't plan on adding this.

The PR I mentioned:
https://github.com/Vaelor/errbot-mattermost-backend/pull/41

**Comment by Atlas974** [comment]
Thank you for your answer. I may work on the problem (or not, depending on how time consuming it gets...). I will propose modifications to the code if I get things right.
